<template><view class="page"><view class="title">公告中心</view>
  <view v-for="item in items" :key="item.id" class="menu-item" @click="open(item.id)"><view class="menu-left"><view class="menu-title"><view class="announcement-title">{{ item.title }} <text v-if="item.announcementType==='RULE_UPDATE'" class="rule-tag">规则更新</text></view><view class="muted">{{ formatDateTime(item.publishedAt) }}</view></view></view><text class="menu-arrow">›</text></view>
  <view v-if="!items.length&&!loading" class="empty">暂无公告</view><view v-if="loading" class="empty">加载中…</view>
</view></template>
<script setup>
import { onPullDownRefresh,onReachBottom,onShow } from '@dcloudio/uni-app';import { ref } from 'vue';import { api } from '../../utils/request';import { formatDateTime } from '../../utils/orderDisplay';import { runPullDownRefresh } from '../../utils/pullDownRefresh';
const items=ref([]);const page=ref(0);const hasMore=ref(true);const loading=ref(false);async function load(reset=false){if(loading.value||(!reset&&!hasMore.value))return;if(reset){items.value=[];page.value=0;hasMore.value=true}loading.value=true;try{const r=await api.announcements({page:page.value});items.value.push(...r.items);page.value++;hasMore.value=r.hasMore}finally{loading.value=false}}function open(id){uni.navigateTo({url:`/pages/announcement-detail/index?id=${encodeURIComponent(id)}`})}onShow(()=>load(true));onReachBottom(()=>load());onPullDownRefresh(()=>runPullDownRefresh(()=>load(true)));
</script>
<style scoped>.menu-item{width:100%;display:flex;align-items:center;justify-content:space-between;box-sizing:border-box;padding:24rpx;background:#fff;border-bottom:1rpx solid #e5efec}.menu-left{min-width:0;flex:1;display:flex;align-items:center}.menu-title{min-width:0;flex:1}.announcement-title{font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rule-tag{font-size:20rpx;color:#2E8FD9;background:#E3F1FD;padding:3rpx 8rpx;border-radius:4px}.menu-arrow{flex-shrink:0;font-size:44rpx;color:#7A93A8;margin-left:20rpx}</style>
