<template><view class="page"><view class="title">账号管理</view>
  <view class="filters"><view class="search-row"><input class="input search" v-model="keyword" placeholder="姓名、学号或手机号" confirm-type="search" @confirm="load(true)"/><button class="search-btn" @click="load(true)">查询</button></view>
    <view class="filter-row"><picker class="filter-picker" :range="roleOptions" range-key="label" :value="roleIndex" @change="changeRole"><view>{{ roleOptions[roleIndex].label }}</view></picker><picker class="filter-picker" :range="statusOptions" range-key="label" :value="statusIndex" @change="changeStatusFilter"><view>{{ statusOptions[statusIndex].label }}</view></picker></view>
  </view>
  <view v-if="errorMessage" class="error-state"><view>{{ errorMessage }}</view><button class="retry" @click="load(true)">重新加载</button></view>
  <view v-else-if="loading&&!items.length" class="empty">账号加载中…</view>
  <template v-else><view v-for="item in items" :key="item.id" class="card account-card"><view class="row"><text class="name">{{ item.realName||'未完善资料' }}</text><text class="status">{{ roleLabel(item.role) }}</text></view><view>学号：{{ item.studentNo||'未填写' }}</view><view>手机号：{{ item.phone||'未填写' }}</view><view>宿舍：{{ dormLabel(item) }}</view><view>账号状态：{{ item.accountStatus==='ACTIVE'?'正常':'已禁用' }}</view><button class="btn" :class="{danger:item.accountStatus==='ACTIVE'}" :loading="operatingId===item.id" @click="changeAccountStatus(item)">{{ item.accountStatus==='ACTIVE'?'禁用账号':'启用账号' }}</button></view><view v-if="!items.length" class="empty">暂无账号数据</view><view v-else-if="!hasMore" class="end">没有更多了</view></template>
</view></template>
<script setup>
import { onPullDownRefresh,onReachBottom,onShow } from '@dcloudio/uni-app';import { ref } from 'vue';import { api } from '../../utils/request';import { useUserStore } from '../../stores/user';import { syncRoleSurface } from '../../utils/roleNavigation';import { runPullDownRefresh } from '../../utils/pullDownRefresh';
const store=useUserStore();const keyword=ref('');const items=ref([]);const page=ref(0);const hasMore=ref(true);const loading=ref(false);const errorMessage=ref('');const operatingId=ref('');
const roleOptions=[{label:'全部角色',value:''},{label:'普通用户',value:'USER'},{label:'管理员',value:'ADMIN'}];const statusOptions=[{label:'全部状态',value:''},{label:'正常',value:'ACTIVE'},{label:'已禁用',value:'DISABLED'}];const roleIndex=ref(0);const statusIndex=ref(0);
function roleLabel(role){return role==='ADMIN'?'管理员':'普通用户'}function dormLabel(item){return item.dormBuildingName?`${item.dormBuildingName} ${item.floorNo||''}层 ${item.roomNo||''}号`:'未填写'}
function changeRole(event){roleIndex.value=Number(event.detail.value);load(true)}function changeStatusFilter(event){statusIndex.value=Number(event.detail.value);load(true)}
async function load(reset=false){if(loading.value||(!reset&&!hasMore.value))return;if(reset){items.value=[];page.value=0;hasMore.value=true}loading.value=true;errorMessage.value='';try{const auth=await syncRoleSurface(store,'SUPER');if(!auth.allowed)return;const result=await api.superAccounts({keyword:keyword.value,page:page.value,role:roleOptions[roleIndex.value].value,accountStatus:statusOptions[statusIndex.value].value});items.value.push(...(result.items||[]));page.value+=1;hasMore.value=result.hasMore===true}catch(error){console.error('account list failed',{action:'super.accountList',page:'账号管理',code:error?.code,message:error?.message});errorMessage.value=error?.message||'账号加载失败，请稍后重试'}finally{loading.value=false}}
function changeAccountStatus(item){const next=item.accountStatus==='ACTIVE'?'DISABLED':'ACTIVE';uni.showModal({title:'确认操作',content:`确认${next==='DISABLED'?'禁用':'启用'}该账号？`,success:async({confirm})=>{if(!confirm||operatingId.value)return;operatingId.value=item.id;try{await api.setSuperAccountStatus({userId:item.id,accountStatus:next});uni.showToast({title:'操作成功',icon:'success'});await load(true)}catch(error){console.error('account status failed',{action:'super.accountStatus',page:'账号管理',code:error?.code,message:error?.message})}finally{operatingId.value=''}}})}
onShow(()=>load(true));onReachBottom(()=>load());onPullDownRefresh(()=>runPullDownRefresh(()=>load(true)));
</script>
<style scoped>.filters{margin-bottom:20rpx}.search-row{display:flex;gap:12rpx}.search{flex:1;margin:0}.search-btn{width:150rpx;background:#3E9BF0;color:#fff;font-size:27rpx}.filter-row{display:flex;gap:12rpx;margin-top:14rpx}.filter-picker{flex:1;padding:20rpx;background:#fff;border:1px solid #C9DFF2;border-radius:6px;text-align:center;color:#2E8FD9}.account-card{line-height:1.8}.name{font-weight:600}.error-state{text-align:center;color:#b42318;padding:70rpx 0}.retry{width:220rpx;margin-top:20rpx;font-size:26rpx}.end{text-align:center;color:#7A93A8;padding:24rpx}</style>
