<template><view class="page"><view class="title">管理员管理</view>
  <view class="tabs"><button class="tab" :class="{active:tab==='ADMINS'}" @click="switchTab('ADMINS')">当前管理员</button><button class="tab" :class="{active:tab==='CANDIDATES'}" @click="switchTab('CANDIDATES')">可任命用户</button></view>
  <view class="search-row"><input class="input search" v-model="keyword" placeholder="姓名、学号或手机号" confirm-type="search" @confirm="load(true)"/><button class="search-btn" @click="load(true)">查询</button></view>
  <view v-if="errorMessage" class="error-state"><view>{{ errorMessage }}</view><button class="retry" @click="load(true)">重新加载</button></view><view v-else-if="loading&&!items.length" class="empty">列表加载中…</view>
  <template v-else><view v-for="item in items" :key="item.id" class="card user-card"><view class="row"><text class="name">{{ item.realName||'未完善资料' }}</text><text class="status">{{ item.accountStatus==='ACTIVE'?'正常':'已禁用' }}</text></view><view>学号：{{ item.studentNo||'未填写' }}</view><view>宿舍楼：{{ item.dormBuildingName||item.dormBuildingId||'未填写' }}</view><button v-if="tab==='ADMINS'" class="btn danger" :loading="operatingId===item.id" @click="setRole(item,'USER')">取消管理员</button><button v-else class="btn" :loading="operatingId===item.id" @click="setRole(item,'ADMIN')">任命管理员</button></view><view v-if="!items.length" class="empty">{{ tab==='ADMINS'?'暂无管理员':'暂无可任命用户' }}</view><view v-else-if="!hasMore" class="end">没有更多了</view></template>
</view></template>
<script setup>
import { onPullDownRefresh,onReachBottom,onShow } from '@dcloudio/uni-app';import { ref } from 'vue';import { api } from '../../utils/request';import { useUserStore } from '../../stores/user';import { syncRoleSurface } from '../../utils/roleNavigation';import { runPullDownRefresh } from '../../utils/pullDownRefresh';
const store=useUserStore();const tab=ref('ADMINS');const keyword=ref('');const items=ref([]);const page=ref(0);const hasMore=ref(true);const loading=ref(false);const errorMessage=ref('');const operatingId=ref('');
function switchTab(value){if(tab.value===value)return;tab.value=value;load(true)}
async function load(reset=false){if(loading.value||(!reset&&!hasMore.value))return;if(reset){items.value=[];page.value=0;hasMore.value=true}loading.value=true;errorMessage.value='';try{const auth=await syncRoleSurface(store,'SUPER');if(!auth.allowed)return;const params=tab.value==='ADMINS'?{page:page.value,keyword:keyword.value,role:'ADMIN'}:{page:page.value,keyword:keyword.value,role:'USER',accountStatus:'ACTIVE',appointable:true};const result=await api.superAccounts(params);items.value.push(...(result.items||[]));page.value+=1;hasMore.value=result.hasMore===true}catch(error){console.error('admin management list failed',{action:'super.accountList',page:'管理员管理',code:error?.code,message:error?.message});errorMessage.value=error?.message||'列表加载失败，请稍后重试'}finally{loading.value=false}}
function setRole(item,role){uni.showModal({title:'确认操作',content:role==='ADMIN'?'确认任命该用户为管理员？':'确认取消该用户的管理员身份？',success:async({confirm})=>{if(!confirm||operatingId.value)return;operatingId.value=item.id;try{await api.setSuperAdminRole({userId:item.id,role});uni.showToast({title:'操作成功',icon:'success'});await load(true)}catch(error){console.error('admin role update failed',{action:'super.adminRole',page:'管理员管理',code:error?.code,message:error?.message})}finally{operatingId.value=''}}})}
onShow(()=>load(true));onReachBottom(()=>load());onPullDownRefresh(()=>runPullDownRefresh(()=>load(true)));
</script>
<style scoped>.tabs{display:flex;gap:12rpx;margin-bottom:18rpx}.tab{flex:1;background:#edf5f2;color:#1d5b50;font-size:27rpx}.tab.active{background:#147a69;color:#fff}.search-row{display:flex;gap:12rpx;margin-bottom:20rpx}.search{flex:1;margin:0}.search-btn{width:150rpx;background:#147a69;color:#fff;font-size:27rpx}.user-card{line-height:1.8}.name{font-weight:600}.error-state{text-align:center;color:#b42318;padding:70rpx 0}.retry{width:220rpx;margin-top:20rpx;font-size:26rpx}.end{text-align:center;color:#6a7d76;padding:24rpx}</style>
