<template><view class="page"><view class="title">操作记录</view>
  <view v-if="errorMessage" class="error-state"><view>{{ errorMessage }}</view><button class="retry" @click="load(true)">重新加载</button></view><view v-else-if="loading&&!items.length" class="empty">记录加载中…</view>
  <template v-else><view v-for="item in items" :key="item.id" class="card log-card"><view class="row"><text class="action">{{ actionLabel(item.action) }}</text><text class="status">{{ targetLabel(item.targetType) }}</text></view><view>操作目标：{{ targetText(item) }}</view><view>操作结果：{{ resultText(item) }}</view><view v-if="snapshotText(item.beforeSnapshot)" class="muted">修改前：{{ snapshotText(item.beforeSnapshot) }}</view><view v-if="snapshotText(item.afterSnapshot)" class="muted">修改后：{{ snapshotText(item.afterSnapshot) }}</view><view class="muted">操作人：{{ item.operatorName||'超级管理员' }}</view><view class="muted">操作时间：{{ formatDateTime(item.createdAt) }}</view></view><view v-if="!items.length" class="empty">暂无操作记录</view><view v-else-if="!hasMore" class="end">没有更多了</view></template>
</view></template>
<script setup>
import { onPullDownRefresh,onReachBottom,onShow } from '@dcloudio/uni-app';import { ref } from 'vue';import { api } from '../../utils/request';import { formatDateTime } from '../../utils/orderDisplay';import { useUserStore } from '../../stores/user';import { syncRoleSurface } from '../../utils/roleNavigation';import { runPullDownRefresh } from '../../utils/pullDownRefresh';
const store=useUserStore();const items=ref([]);const page=ref(0);const hasMore=ref(true);const loading=ref(false);const errorMessage=ref('');
function actionLabel(value){return({SYSTEM_RULE_UPDATE:'规则修改',ACCOUNT_DISABLE:'账号禁用',ACCOUNT_ENABLE:'账号启用',ADMIN_APPOINT:'任命管理员',ADMIN_REVOKE:'取消管理员',ANNOUNCEMENT_CREATE:'创建公告',ANNOUNCEMENT_UPDATE:'编辑公告',ANNOUNCEMENT_PUBLISH:'发布公告',ANNOUNCEMENT_OFFLINE:'下架公告'})[value]||'平台治理操作'}
function targetLabel(value){return({SYSTEM_RULE:'规则',USER:'账号',ANNOUNCEMENT:'公告'})[value]||'系统'}function targetText(item){if(item.targetType==='SYSTEM_RULE')return `业务规则${item.ruleVersion?`（版本 ${item.ruleVersion}）`:''}`;return item.targetName||item.afterSnapshot?.title||item.beforeSnapshot?.title||item.targetId||'未记录'}
function snapshotText(value){if(!value||typeof value!=='object')return'';if(value.accountStatus)return value.accountStatus==='ACTIVE'?'正常':'已禁用';if(value.role)return value.role==='ADMIN'?'管理员':'普通用户';if(value.title)return value.title;if(value.version)return `规则版本 ${value.version}`;if(value.status)return value.status==='PUBLISHED'?'已发布':'已下架';return''}
function resultText(item){return snapshotText(item.afterSnapshot)||'操作成功'}
async function load(reset=false){if(loading.value||(!reset&&!hasMore.value))return;if(reset){items.value=[];page.value=0;hasMore.value=true}loading.value=true;errorMessage.value='';try{const auth=await syncRoleSurface(store,'SUPER');if(!auth.allowed)return;const result=await api.superLogs({page:page.value});items.value.push(...(result.items||[]));page.value+=1;hasMore.value=result.hasMore===true}catch(error){console.error('super operation logs failed',{action:'super.operationLogs',page:'操作记录',code:error?.code,message:error?.message});errorMessage.value=error?.message||'操作记录加载失败，请稍后重试'}finally{loading.value=false}}
onShow(()=>load(true));onReachBottom(()=>load());onPullDownRefresh(()=>runPullDownRefresh(()=>load(true)));
</script>
<style scoped>.log-card{line-height:1.8}.action{font-weight:600}.error-state{text-align:center;color:#b42318;padding:70rpx 0}.retry{width:220rpx;margin-top:20rpx;font-size:26rpx}.end{text-align:center;color:#6a7d76;padding:24rpx}</style>
